"""create coins, price_snapshots and alerts tables

Revision ID: 0f61ff8c492b
Revises:
Create Date: 2026-10-02 13:29:10.542169

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f61ff8c492b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coingecko_id", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coins_coingecko_id"), "coins", ["coingecko_id"], unique=True
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coin_id", sa.Integer(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "above", "below", name="alertdirection", native_enum=False, length=10
            ),
            nullable=False,
        ),
        sa.Column("target_price", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("target_price > 0", name="ck_alerts_target_price_positive"),
        sa.ForeignKeyConstraint(["coin_id"], ["coins.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_coin_id"), "alerts", ["coin_id"], unique=False)
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coin_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price > 0", name="ck_price_snapshots_price_positive"),
        sa.ForeignKeyConstraint(["coin_id"], ["coins.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_snapshots_coin_id_fetched_at",
        "price_snapshots",
        ["coin_id", "fetched_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_snapshots_coin_id_fetched_at", table_name="price_snapshots")
    op.drop_table("price_snapshots")
    op.drop_index(op.f("ix_alerts_coin_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_coins_coingecko_id"), table_name="coins")
    op.drop_table("coins")
    # ### end Alembic commands ###
