"""add triggered_price and notified_at to alerts

Revision ID: 7fc5d6ea8c13
Revises: 0f61ff8c492b
Create Date: 2026-10-07 12:19:10.205344

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7fc5d6ea8c13'
down_revision: str | Sequence[str] | None = '0f61ff8c492b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('triggered_price', sa.Numeric(precision=30, scale=12), nullable=True))
    op.add_column('alerts', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'notified_at')
    op.drop_column('alerts', 'triggered_price')
    # ### end Alembic commands ###
